# Generated by Django 3.2.25 on 2025-04-21 12:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[tasks.validators.validate_file_size, tasks.validators.validate_file_type], verbose_name='file')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('fitness', 'Fitness'), ('finance', 'Finance'), ('misc', 'Miscellaneous')], default='misc', max_length=20)),
                ('state', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('overdue', 'Overdue')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date'],
            },
        ),
    ]
