# Generated by Django 3.2.25 on 2025-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.CharField(blank=True, max_length=255, default='default/default_image_omif5j', verbose_name='image'),
        ),
    ]
