# Generated by Django 3.2.25 on 2025-05-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
    ]
